// Code generated by go-swagger; DO NOT EDIT.

// Package restapi recipe-rolodex
//
//  Repository of recipe information
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /rolodex
//  Version: 0.0.1
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
