// Code generated by go-swagger; DO NOT EDIT.

package recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetRecipeHandlerFunc turns a function with the right signature into a get recipe handler
type GetRecipeHandlerFunc func(GetRecipeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRecipeHandlerFunc) Handle(params GetRecipeParams) middleware.Responder {
	return fn(params)
}

// GetRecipeHandler interface for that can handle valid get recipe params
type GetRecipeHandler interface {
	Handle(GetRecipeParams) middleware.Responder
}

// NewGetRecipe creates a new http.Handler for the get recipe operation
func NewGetRecipe(ctx *middleware.Context, handler GetRecipeHandler) *GetRecipe {
	return &GetRecipe{Context: ctx, Handler: handler}
}

/*GetRecipe swagger:route GET /recipe recipe getRecipe

get details about a recipe

Retrieve details about a recipe given a recipeID


*/
type GetRecipe struct {
	Context *middleware.Context
	Handler GetRecipeHandler
}

func (o *GetRecipe) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRecipeParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
