// Code generated by go-swagger; DO NOT EDIT.

package recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewGetRecipeParams creates a new GetRecipeParams object
// no default values defined in spec.
func NewGetRecipeParams() GetRecipeParams {

	return GetRecipeParams{}
}

// GetRecipeParams contains all the bound params for the get recipe operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetRecipe
type GetRecipeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*a recipe ID
	  Required: true
	  In: query
	*/
	RecipeID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetRecipeParams() beforehand.
func (o *GetRecipeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qRecipeID, qhkRecipeID, _ := qs.GetOK("recipeID")
	if err := o.bindRecipeID(qRecipeID, qhkRecipeID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindRecipeID binds and validates parameter RecipeID from query.
func (o *GetRecipeParams) bindRecipeID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("recipeID", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("recipeID", "query", raw); err != nil {
		return err
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("recipeID", "query", "int64", raw)
	}
	o.RecipeID = value

	return nil
}
