// Code generated by go-swagger; DO NOT EDIT.

package recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/cstkpk/recipeRolodex/models"
)

// NewPostRecipeParams creates a new PostRecipeParams object
// no default values defined in spec.
func NewPostRecipeParams() PostRecipeParams {

	return PostRecipeParams{}
}

// PostRecipeParams contains all the bound params for the post recipe operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostRecipe
type PostRecipeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*new recipe details
	  Required: true
	  In: body
	*/
	NewRecipe *models.NewRecipe
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostRecipeParams() beforehand.
func (o *PostRecipeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.NewRecipe
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("newRecipe", "body"))
			} else {
				res = append(res, errors.NewParseError("newRecipe", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.NewRecipe = &body
			}
		}
	} else {
		res = append(res, errors.Required("newRecipe", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
