// Code generated by go-swagger; DO NOT EDIT.

package ready

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cstkpk/recipeRolodex/models"
)

// GetReadyOKCode is the HTTP code returned for type GetReadyOK
const GetReadyOKCode int = 200

/*GetReadyOK post successful responses

swagger:response getReadyOK
*/
type GetReadyOK struct {

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewGetReadyOK creates GetReadyOK with default headers values
func NewGetReadyOK() *GetReadyOK {

	return &GetReadyOK{}
}

// WithPayload adds the payload to the get ready o k response
func (o *GetReadyOK) WithPayload(payload *models.ReturnCode) *GetReadyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get ready o k response
func (o *GetReadyOK) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReadyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetReadyInternalServerErrorCode is the HTTP code returned for type GetReadyInternalServerError
const GetReadyInternalServerErrorCode int = 500

/*GetReadyInternalServerError internal service error

swagger:response getReadyInternalServerError
*/
type GetReadyInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewGetReadyInternalServerError creates GetReadyInternalServerError with default headers values
func NewGetReadyInternalServerError() *GetReadyInternalServerError {

	return &GetReadyInternalServerError{}
}

// WithPayload adds the payload to the get ready internal server error response
func (o *GetReadyInternalServerError) WithPayload(payload *models.ReturnCode) *GetReadyInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get ready internal server error response
func (o *GetReadyInternalServerError) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReadyInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetReadyDefault unexpected error

swagger:response getReadyDefault
*/
type GetReadyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewGetReadyDefault creates GetReadyDefault with default headers values
func NewGetReadyDefault(code int) *GetReadyDefault {
	if code <= 0 {
		code = 500
	}

	return &GetReadyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get ready default response
func (o *GetReadyDefault) WithStatusCode(code int) *GetReadyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get ready default response
func (o *GetReadyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get ready default response
func (o *GetReadyDefault) WithPayload(payload *models.ReturnCode) *GetReadyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get ready default response
func (o *GetReadyDefault) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReadyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
