// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Recipe recipe
// swagger:model Recipe
type Recipe struct {

	// author
	Author string `json:"author,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// link
	Link string `json:"link,omitempty"`

	// season
	Season string `json:"season,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this recipe
func (m *Recipe) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Recipe) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Recipe) UnmarshalBinary(b []byte) error {
	var res Recipe
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
